[versions]
springBoot = "3.4.1"
springDependencyManagement = "1.1.6"
lombok = "1.18.34"
junit = "5.10.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
